// keygen generates obfuscated key fragments for the vault encryption system.
// Each run produces 4 fragments scattered across different Go files under internal/vault/.
//
// The real AES-256 key is: SHA256(interleave(deobfuscate(kp1), deobfuscate(kp2), deobfuscate(kp3), deobfuscate(kp4)))
// Fragments are stored obfuscated so grep/strings cannot find a complete key.
//
// Usage:
//
//	go run cmd/keygen/main.go                    # random key
//	go run cmd/keygen/main.go --seed=my-secret    # deterministic (for CI)
package main

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	seed := flag.String("seed", "", "deterministic seed string (for CI reproducibility)")
	flag.Parse()

	var masterSeed [32]byte
	if *seed != "" {
		masterSeed = sha256.Sum256([]byte(*seed))
	} else {
		if _, err := rand.Read(masterSeed[:]); err != nil {
			fmt.Fprintf(os.Stderr, "rand.Read failed: %v\n", err)
			os.Exit(1)
		}
	}

	// Derive 4 sub-seeds
	sub1 := sha256.Sum256(append(masterSeed[:], 0x01))
	sub2 := sha256.Sum256(append(masterSeed[:], 0x02))
	sub3 := sha256.Sum256(append(masterSeed[:], 0x03))
	sub4 := sha256.Sum256(append(masterSeed[:], 0x04))

	// Each fragment is 8 bytes
	kp1 := sub1[:8]
	kp2 := sub2[:8]
	kp3 := sub3[:8]
	kp4 := sub4[:8]

	// Derive the real AES key
	realKey := deriveRealKey(kp1, kp2, kp3, kp4)

	// Obfuscate each fragment differently
	obf1 := xorBytes(kp1, 0x5A)
	obf2 := reverseBytes(kp2)
	obf3 := rotateLeftBytes(kp3, 3)
	obf4 := xorBytes(kp4, 0xA5)

	root := filepath.Join("internal", "vault")

	writeFragment(filepath.Join(root, "kp_env.go"), "kp_env.go", obf1, "xorBytes(kp1, 0x5A) = obf1 → decode: xorBytes(obf1, 0x5A)")
	writeFragment(filepath.Join(root, "kp_config.go"), "kp_config.go", obf2, "reverseBytes(kp2) = obf2 → decode: reverseBytes(obf2)")
	writeFragment(filepath.Join(root, "kp_runtime.go"), "kp_runtime.go", obf3, "rotateLeftBytes(kp3, 3) = obf3 → decode: rotateRightBytes(obf3, 3)")
	writeFragment(filepath.Join(root, "kp_tool.go"), "kp_tool.go", obf4, "xorBytes(kp4, 0xA5) = obf4 → decode: xorBytes(obf4, 0xA5)")

	// Write derive.go (the deobfuscation + assembly logic)
	writeDeriveGo(filepath.Join(root, "derive.go"))

	// Print the real key for use by the encrypt tool
	fmt.Print(hex.EncodeToString(realKey))
}

func deriveRealKey(kp1, kp2, kp3, kp4 []byte) []byte {
	// Interleave: p1[0]|p2[0]|p3[0]|p4[0]|p1[1]|...
	combined := make([]byte, 0, 32)
	for i := 0; i < 8; i++ {
		combined = append(combined, kp1[i], kp2[i], kp3[i], kp4[i])
	}
	hash := sha256.Sum256(combined)
	return hash[:]
}

func xorBytes(data []byte, mask byte) []byte {
	out := make([]byte, len(data))
	for i := range data {
		out[i] = data[i] ^ mask
	}
	return out
}

func reverseBytes(data []byte) []byte {
	out := make([]byte, len(data))
	for i := range data {
		out[i] = data[len(data)-1-i]
	}
	return out
}

func rotateLeftBytes(data []byte, n int) []byte {
	out := make([]byte, len(data))
	for i := range data {
		out[i] = data[(i+n)%len(data)]
	}
	return out
}

func writeFragment(path, filename string, data []byte, comment string) {
	// Write as a compile-time constant to avoid Go's string literal analysis
	content := fmt.Sprintf(`// Code generated by keygen; DO NOT EDIT.
// %s
package vault

// obfuscated key fragment — deobfuscated at runtime by derive.go
var %s = [%d]byte{%s}
`, comment, varNameForFile(filename), len(data), byteArrayLiteral(data))

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("  wrote %s\n", path)
}

func varNameForFile(filename string) string {
	switch filename {
	case "kp_env.go":
		return "kpEnv"
	case "kp_config.go":
		return "kpConfig"
	case "kp_runtime.go":
		return "kpRuntime"
	case "kp_tool.go":
		return "kpTool"
	default:
		return "kpUnknown"
	}
}

func byteArrayLiteral(data []byte) string {
	s := ""
	for i, b := range data {
		if i > 0 {
			s += ", "
		}
		s += fmt.Sprintf("0x%02x", b)
	}
	return s
}

func writeDeriveGo(path string) {
	content := `// Code generated by keygen; DO NOT EDIT.
// derive.go assembles the real AES-256 key from 4 obfuscated fragments.
// The fragments are deobfuscated, interleaved, and hashed at runtime.
package vault

import "crypto/sha256"

// deriveKey assembles the 32-byte AES-256 key.
//
//go:noinline
func deriveKey() []byte {
	p1 := decodeXor(kpEnv[:], 0x5a)
	p2 := reverse(kpConfig[:])
	p3 := rotateRight(kpRuntime[:], 3)
	p4 := decodeXor(kpTool[:], 0xa5)

	combined := make([]byte, 0, 32)
	for i := 0; i < 8; i++ {
		combined = append(combined, p1[i], p2[i], p3[i], p4[i])
	}
	hash := sha256.Sum256(combined)
	return hash[:]
}

//go:noinline
func decodeXor(data []byte, mask byte) []byte {
	out := make([]byte, len(data))
	for i := range data {
		out[i] = data[i] ^ mask
	}
	return out
}

//go:noinline
func reverse(data []byte) []byte {
	out := make([]byte, len(data))
	for i := range data {
		out[i] = data[len(data)-1-i]
	}
	return out
}

//go:noinline
func rotateRight(data []byte, n int) []byte {
	out := make([]byte, len(data))
	for i := range data {
		out[i] = data[(i-n+len(data))%len(data)]
	}
	return out
}
`
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("  wrote %s\n", path)
}
